---
 - hosts: localhost
  #Variables
   vars:
     replicas: 2
   tasks:
   - name: Create a Deployment for go App
     k8s:
        api_version: v1
        namespace: default
        definition:
          kind: Deployment
          metadata:
            labels:
              app: hello-go
            name: hello-deploy
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: hello-go
            template:
              metadata:
                labels:
                  app: hello-go
              spec:
                containers:
                  - name: hello-go
                    image: "{{ image_id }}" 
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 8000
                        protocol: TCP

  
   - name: Create a Service for Hello Go.
     k8s:
       state: present
       definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-go
            namespace: default
          spec:
            type: LoadBalancer
            ports:
            - port: 8000
              targetPort: 8000
            selector:
              app: hello-go     
