apiVersion: v1
kind: Service
metadata:
  name: jonathanjulius85/webapp
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort
